#include<iostream>
using namespace std;
int main(){
    for(int i = 1; i<=4; i++){
        for(int j = 1; j<=5; j++){
            cout<<" ";
        }
        for(int k = i; k<=i; k++){
                cout<<"    *";
            
        
        }
         cout<<endl;
}
for(int a = 1; a<=9; a++){
    cout<<" *";
 }
 cout<<endl;
    for(int i = 1; i<=4; i++){
        for(int j = 1; j<=5; j++){
            cout<<" ";
        }
        for(int k = i; k<=i; k++){
            cout<<"    *";
        }
        cout<<endl;
    }
}